/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author Ana
 */
public class FrmReloj extends javax.swing.JFrame {

    /**
     * Creates new form FrmReloj
     */
    public FrmReloj() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopMensaje = new javax.swing.JOptionPane();
        txtReloj = new javax.swing.JTextField();
        btnSaludar = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reloj");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtReloj.setEditable(false);
        txtReloj.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtReloj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 510, 170));

        btnSaludar.setText("SALUDAR");
        getContentPane().add(btnSaludar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 110, 50));

        btnParar.setText("PARAR");
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });
        getContentPane().add(btnParar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 110, 50));

        btnIniciar.setText("INICIAR");
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 110, 50));

        lblMensaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 216, 510, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReloj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIniciar;
    public javax.swing.JButton btnParar;
    public javax.swing.JButton btnSaludar;
    public javax.swing.JOptionPane jopMensaje;
    public javax.swing.JLabel lblMensaje;
    public javax.swing.JTextField txtReloj;
    // End of variables declaration//GEN-END:variables
}
