/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

/**
 *
 * @author Ana
 */
public class MenuCliente extends javax.swing.JFrame {

    /** Creates new form MenuCliente */
    public MenuCliente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMetodosPago = new javax.swing.JButton();
        lblUsuarioActivo = new javax.swing.JLabel();
        btnInfoUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú principal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMetodosPago.setText("ADMINISTRAR MÉTODOS DE PAGO");
        getContentPane().add(btnMetodosPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 274, 80));

        lblUsuarioActivo.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        getContentPane().add(lblUsuarioActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 150, 30));

        btnInfoUsuario.setText("INFORMACIÓN USUARIO");
        getContentPane().add(btnInfoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 280, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnInfoUsuario;
    public javax.swing.JButton btnMetodosPago;
    public javax.swing.JLabel lblUsuarioActivo;
    // End of variables declaration//GEN-END:variables

}
